version: '3.3'
services:
    Qbittorrent-openvpn:
        cap_add:
            - NET_ADMIN
        restart: always
        volumes:
            - 'local/path/for/qbittorentconf:/config'
            - 'local/path/for/downloads:/downloads'
        environment:
            - OPENVPN_PROVIDER=SURFSHARK
            - OPENVPN_CONFIG=nl-ams_tcp,nl-ams-st001_tcp,es-bcn_tcp,es-mad_tcp,es-vlc_tcp
            - OPENVPN_USERNAME=<ID>
            - OPENVPN_PASSWORD=<Pass>
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '8080:8080'
        image: qtorrent
